language: cpp
sudo: false
branches:
  only:
  - master
  - travis
  - /^v\d+(\.\d+)+$/
  - travis_build
  - remove_hdf5
  - /test/
matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages:
        - gfortran
        - zlib1g-dev
        - libhdf5-dev
  - os: osx
    osx_image: xcode10.4.4
    sudo: required
before_install:
      #curl -L -o gfortran-7.1-bin.tgz -fs "https://downloads.sourceforge.net/project/hpc/hpc/g95/gfortran-7.1-bin.tar.gz?r=&ts=1508458128&use_mirror=svwh"
      #gunzip gfortran-7.1-bin.tgz
      #sudo tar -xf gfortran-7.1-bin.tar -C /
      #sudo chown -R $(whoami) /usr/local
      #sudo chown -R $(whoami) /Library/Caches/Homebrew
      #brew update
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
    HOMEBREW_NO_AUTO_UPDATE=1 brew install szip
    HOMEBREW_NO_AUTO_UPDATE=1 brew install hdf5@1.8
    export HOMEBREW_NO_INSTALL_CLEANUP=1
    brew info hdf5
    h5cc -show
    # echo 'export PATH="/usr/local/Cellar/hdf5@1.8/1.8.21_1/bin:$PATH"' >> ~/.bash_profile
    # export LDFLAGS="-L/usr/local/Cellar/hdf5@1.8/1.8.21_1/include"
    # export CPPFLAGS="-I/usr/local/Cellar/hdf5@1.8/1.8.21_1/include"
    ls /usr/local/opt/hdf5@1.8/include | grep -i "hdf"
    echo "##########################"
    echo "##########################"
    echo "##########################"
    ls -la /usr/local/Cellar/hdf5/1.10.5_1/lib
      # brew install szip
      rm '/usr/local/include/c++'
      #brew install --verbose --debug --force hdf5@1.8 --c++11
      # brew install hdf5@1.12
    fi
    
script: .travis/build.sh

# for osx, use otool -L to find dependencies
# for linux, use ldd to find dependencies
# copy dependent libraries to build/bin (excluding those already in the build/bin directory ... -v "build")
# (for mac only) edit executables and libraries using install_name_tool to make relocatable
# create compressed tar file to deploy to github
before_deploy:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd build/bin
      ls *_x64   | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.dylib | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.dylib | awk '{print $1}' | xargs -I '{}' otool -L '{}' | grep ")" | grep -v "build" | grep -v "System" | awk '{print $1}' | xargs -I '{}' cp -vn '{}' . || true
      chmod u+w,+x * 
      tar czvf ../mac64_bad_paths.tgz .
      ../../.travis/install_name_tool_macos.sh
      tar czvf ../mac64.tgz --dereference .
      cd ../..
    else
      cd build/bin
      ls *_x64   | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.so    | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      ls *.so    | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true
      chmod u+w,+x *
      tar czvf ../linux64.tgz --dereference .
      cd ../..
    fi

deploy:
  provider: releases
  api_key:
    secure: REC02vGjadieRTgPaecS4endNGzoZXdyd2+zCIPRQmTkoxjtTEt4Um4qoTc3jxiLU9iuBLKRnFzlo2cfqCF/fuxGYZLutBXvg/D3O0KQbu2WK/khT0O+u6j4I4eJ6R7C3MF//Rbo6KLkQf0u2PzqtOxevAXbDbsNMRrqD7kGWbhw/ABmOd8xj7dWLrzX5zu5M7im0V3kSR8DmUn7mZjDZwyfjo6uNQNjRcUSNLyICiJ1yIDgjbAG3bi7fyxOv82zTNKVbt3og9MglhcWSMcOwwZXBhpGPoEtjnKqNzqnSvZs9Uf+0tAsaipzUS/qLS/l0FGsu4AlWdl133Fs/9/qNws/XXETxUOYxEo0UQUGPfEmolUVrISdHUc/OkfNt+5iow0pZvtqDbOVHV1R5G3U/y3jdcDn2druyHnek2QeTRzClvS3FRCEt1D4I/zVKHqJaolb2BVgyzGQnk22mC8GVGICetxfB7j/XRMVCofaVAI/867XcvDfQolweQRF6E/a4mf1Tlhc1aOXcxxAJTh56pQX+w6N+VqVn/pEaXY83uunXkrhQp1SDqtQ6oe611MLWOgcqcovTtl2Ge+lheJvAiFbAeZfNAYvISu/mKqz1nhEr17fu0g4ncOGlU0v0SjI0O5kd49CawQd+dfVLjOzL33BvgpmUEPDh0Q8/4bQk2k=
  file_glob: true
  file: build/*.tgz
  skip_cleanup: true
  on:
    repo: vcfrmgit/vcell-solvers
    tags: true
    all_branches: true
